
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;


namespace ET
{
    public sealed partial class LocalizeConfig_CHS : ALocalizeConfig
    {
        public LocalizeConfig_CHS(ByteBuf _buf)  : base(_buf) 
        {
            TextCHS = _buf.ReadString();
            PostInit();
        }
    
        public static LocalizeConfig_CHS DeserializeLocalizeConfig_CHS(ByteBuf _buf)
        {
            return new LocalizeConfig_CHS(_buf);
        }
    
        public readonly string TextCHS;
       
        public const int __ID__ = -887446246;
        public override int GetTypeId() => __ID__;
    
        public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
        {
            base.Resolve(_tables);
            
            PostResolve();
        }
    
        public override string ToString()
        {
            return "{ "
            + "key:" + Key + ","
            + "TextCHS:" + TextCHS + ","
            + "}";
        }
        
        partial void PostInit();
        partial void PostResolve();
    }

}
