//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System;


namespace ET
{
   
public partial class Tables
{   
    private System.Collections.Generic.Dictionary<string, IConfigCategory> tables;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        tables = new System.Collections.Generic.Dictionary<string, IConfigCategory>();
        StartMachineConfigCategory StartMachineConfigCategory = new StartMachineConfigCategory(loader("startmachineconfigcategory")); 
        tables.Add("StartMachineConfigCategory", StartMachineConfigCategory);
        StartProcessConfigCategory StartProcessConfigCategory = new StartProcessConfigCategory(loader("startprocessconfigcategory")); 
        tables.Add("StartProcessConfigCategory", StartProcessConfigCategory);
        StartSceneConfigCategory StartSceneConfigCategory = new StartSceneConfigCategory(loader("startsceneconfigcategory")); 
        tables.Add("StartSceneConfigCategory", StartSceneConfigCategory);
        StartZoneConfigCategory StartZoneConfigCategory = new StartZoneConfigCategory(loader("startzoneconfigcategory")); 
        tables.Add("StartZoneConfigCategory", StartZoneConfigCategory);
        AIConfigCategory AIConfigCategory = new AIConfigCategory(loader("aiconfigcategory")); 
        tables.Add("AIConfigCategory", AIConfigCategory);
        UnitConfigCategory UnitConfigCategory = new UnitConfigCategory(loader("unitconfigcategory")); 
        tables.Add("UnitConfigCategory", UnitConfigCategory);

        PostInit();
        StartMachineConfigCategory.Resolve(tables); 
        StartProcessConfigCategory.Resolve(tables); 
        StartSceneConfigCategory.Resolve(tables); 
        StartZoneConfigCategory.Resolve(tables); 
        AIConfigCategory.Resolve(tables); 
        UnitConfigCategory.Resolve(tables); 
        PostResolve();
    }
    
    public void LoadOneConfig(Type type, Func<string, ByteBuf> loader)
    {
        tables[type.Name] = Activator.CreateInstance(type, loader(type.Name.ToString().ToLower())) as IConfigCategory;
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        StartMachineConfigCategory.Instance.TranslateText(translator); 
        StartProcessConfigCategory.Instance.TranslateText(translator); 
        StartSceneConfigCategory.Instance.TranslateText(translator); 
        StartZoneConfigCategory.Instance.TranslateText(translator); 
        AIConfigCategory.Instance.TranslateText(translator); 
        UnitConfigCategory.Instance.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}